version: 1
formatters:
    simple:
        class: logging.Formatter
        format: '[%(asctime)s] %(levelname)s: %(message)-15s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    log_handler:
        class: logging.FileHandler
        filename: debug.log
        level: DEBUG
        formatter: simple
    stream_handler:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        level: INFO
loggers:
    stackoverflow_analytics:
        level: DEBUG
        handlers: [log_handler, stream_handler]
root:
    level: DEBUG
    handlers: [log_handler, stream_handler]