apiVersion: apps/v1
kind: Deployment
metadata:
 name: online-inference-blue
 labels:
   app: online-inference
spec:
 replicas: 6
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 6
     maxUnavailable: 0
 selector:
   matchLabels:
     app: online-inference
 template:
   metadata:
     name: online-inference-blue
     labels:
       app: online-inference
   spec:
     containers:
       - image: pollytur/online-inference:v2
         imagePullPolicy: "Always"
         name: online-inference
         ports:
           - containerPort: 8000
         readinessProbe:
           httpGet:
             path: /healt_check
             port: 8000
           initialDelaySeconds: 5
           periodSeconds: 3