apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replica
  labels:
    app: online-inference-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference-replica
  template:
    metadata:
      name: online-inference-replica
      labels:
        app: online-inference-replica
    spec:
      containers:
        - image: pollytur/online-inference:v1
          name: online-inference
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healt_check
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healt_check
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 3