apiVersion: v1
kind: Pod
metadata:
  name: online-inference-2
  labels:
    app: online-inference-2
spec:
  containers:
    - image: pollytur/online-inference:v2
      name: online-inference-2
      #imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "2Gi"
          cpu: "250m"
        limits:
          memory: "4Gi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /health_check
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health_check
          port: 8000
        initialDelaySeconds: 40
        periodSeconds: 3