apiVersion: v1
kind: Deployment
metadata:
 name: online-inference-rolling
 labels:
   app: online-inference
spec:
 replicas: 6
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 3
     maxUnavailable: 2
 selector:
   matchLabels:
     app: online-inference
 template:
   metadata:
     name: online-inference
     labels:
       app: online-inference
   spec:
     containers:
       - image: pollytur/online-inference:v2
         name: online-inference
         ports:
           - containerPort: 8000