apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: pollytur/online-inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "2Gi"
          cpu: "250m"
        limits:
          memory: "4Gi"
          cpu: "500m"